Gory/urls.py
from django.urls import path
from .import views

#Konfifguracjha URL
urlpatterns = [
    path('hello', views.say_hello, name='home'),
    path('register/', views.registerPage, name='register_page'),
    path('login/', views.loginPage, name='login_page'),
    path('logout/', views.logoutUser, name='logout'),
    path('test/', views.test, name='test'),
    #path('trasa/', views.zaplanuj_trase, name='zaplanuj_trase'),
    #path('trasa/', views.zaplanuj_trase, name='trasa')
    path('trasa/', views.zaplanuj_trase, name='zaplanuj_trase'),
    path('dodaj_trase/', views.dodaj_trase, name='dodaj_trase'),  # Dodaj ścieżkę do widoku dodawania trasy
    path('dodaj_szczyt/', views.dodaj_szczyt, name='dodaj_szczyt'),
    path('dodaj_wyprawe/', views.dodaj_wyprawe, name='dodaj_wyprawe'),
    path('lista_wypraw/', views.lista_wypraw, name='lista_wypraw'),
    path('ukoncz_wyprawe/<int:wyprawa_id>/', views.ukoncz_wyprawe, name='ukoncz_wyprawe'),
    path('usun_wyprawe/<int:wyprawa_id>/', views.usun_wyprawe, name='usun_wyprawe'),
    path('zgloszenie/', views.zgloszenie, name='zgloszenie'),
    path('widok_ratownika/', views.widok_ratownika, name='widok_ratownika'),
    path('widok_ratownika/<int:zgloszenie_id>/', views.widok_ratownika, name='widok_ratownika'),
    path('przydziel_oddzial_ratunkowy/', views.przydziel_oddzial_ratunkowy, name='przydziel_oddzial_ratunkowy'),
    path('historia-oddzialow/<int:zgloszenie_id>/', views.historia_oddzialow, name='historia_oddzialow'),



    


]

Ratownictwo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('Gory/', include('Gory.urls'))
    
]

Gory/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from django import forms


User = get_user_model()
class Szczyt(models.Model):
    nazwa = models.CharField(max_length=100)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='trasy', null=True, default=None)
    godzina_wyjscia = models.DateTimeField(null=True, blank=True)  # Godzina wyjścia
    punkt_na_mapie = models.CharField(max_length=100, null=True, blank=True)  # Punkt na mapie
    godzina_zakonczenia = models.DateTimeField(null=True, blank=True)  # Godzina zakończenia
    ukonczona = models.BooleanField(default=False)  # Pole oznaczające, czy trasa została ukończona
    wybrany_szczyt = models.ForeignKey('self', on_delete=models.SET_NULL, null=True, blank=True)

class Trasa(models.Model):
    identyfikator = models.CharField(max_length=100)
    nazwa = models.CharField(max_length=100)
    czas_trwania = models.IntegerField()
    schroniska = models.TextField()
    notatka_o_szycie = models.TextField()
    wysokosc_szczytu = models.IntegerField()
    kolor_szlaku = models.CharField(max_length=50, default='Domyślny Kolor')
    pasmo_gorskie = models.CharField(max_length=50)
   

    def __str__(self):
        return self.nazwa
    
class Wyprawa(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='wyprawy', null=True, default=None)
    nazwa_szczytu = models.CharField(max_length=100)
    godzina_wyjscia = models.DateTimeField(null=True, blank=True)
    godzina_zakonczenia = models.DateTimeField(null=True, blank=True)
    ukonczona = models.BooleanField(default=False)
    def __str__(self):
        return f"Wyprawa na {self.nazwa_szczytu}"
    
class WyprawaForm(forms.ModelForm):
    class Meta:
        model = Wyprawa
        fields = ['nazwa_szczytu', 'godzina_wyjscia', 'godzina_zakonczenia', 'ukonczona']

class OddzialRatowniczy(models.Model):
    nazwa = models.CharField(max_length=100)
    kontakt = models.CharField(max_length=100)
    dostepnosc = models.BooleanField(default=True)
    przypisane_zgloszenia = models.ManyToManyField('Zgloszenie', related_name='przypisane_oddzialy', blank=True)

    def __str__(self):
        return self.nazwa

class Zgloszenie(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='zgloszenia')
    trasa = models.ForeignKey('Trasa', on_delete=models.CASCADE)
    godzina_wyruszenia = models.DateTimeField()
    potrzebuje_pomocy = models.BooleanField(default=False)
    wyruszyl_na_pomoc = models.BooleanField(default=False)
    oddzial_ratowniczy = models.ForeignKey(OddzialRatowniczy, on_delete=models.SET_NULL, null=True, blank=True)
    historia_oddzialow = models.ManyToManyField(OddzialRatowniczy, related_name='historia_zgloszen', blank=True)

    def __str__(self):
        if self.user:
            return f"Zgłoszenie użytkownika {self.user.username} na trasie {self.trasa.nazwa}"
        else:
            return f"Zgłoszenie bez przypisanego użytkownika na trasie {self.trasa.nazwa}"

    class Meta:
        ordering = ['-godzina_wyruszenia']

Gory/views.py
import datetime
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponse, JsonResponse
from django.contrib.auth.forms import UserCreationForm

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
# Create your views here.
from .models import *
from .forms import CreateUserForm, SzczytForm, WyruszenieOddzialuForm, ZgloszenieForm
from .forms import TrasaForm
from .forms import DodajTraseForm
from .forms import SzczytForm
from .forms import WyprawaForm
from django.core.mail import send_mail



def say_hello(requset):
   return render(requset, 'index.html')
def registerPage(request):
    form = CreateUserForm()
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Konto Zostało Stworzone")

            return redirect('login_page')
    context = {'form':form}
    return render(request, 'register.html', context)

def loginPage(request):
    context = {}  # Zdefiniowanie zmiennej 'context' przed jej użyciem

    if request.method == 'POST':
      username = request.POST.get('username')
      password = request.POST.get('password')

      user = authenticate(request, username=username, password=password)

      if user is not  None:
          login(request,user)
          return redirect('home')
      else:
          messages.info(request, 'Nazwa lub Hasło są niepoprawne')
    context = {}
    return render(request, 'login.html', context)
def logoutUser(request):
    logout(request)
    return redirect('login_page')

def test(requset):
   return render(requset, 'test.html')
#Nowe
from django.shortcuts import render
from .models import Trasa

from django.shortcuts import render
from .models import Trasa

@login_required
def zaplanuj_trase(request):
    if request.method == 'POST':
        szlak = request.POST.get('szlak')

        try:
            trasa = Trasa.objects.get(nazwa=szlak)
        except Trasa.DoesNotExist:
            trasa = None

        return render(request, 'trasa.html', {'trasa': trasa})

    return render(request, 'trasa.html')

@login_required
def dodaj_trase(request):
    if request.method == 'POST':
        form = DodajTraseForm(request.POST)
        if form.is_valid():
            trasa = form.save(commit=False)
            trasa.user = request.user  # Przypisz trasę do zalogowanego użytkownika
            trasa.save()
            messages.success(request, 'Trasa została dodana pomyślnie.')
            return redirect('trasa')
        else:
            messages.error(request, 'Proszę wypełnić formularz poprawnie.')
    else:
        form = DodajTraseForm()

    trasy = Trasa.objects.filter(user=request.user)  # Pobierz trasy użytkownika
    return render(request, 'trasa.html', {'form': form, 'trasy': trasy})

def dodaj_szczyt(request):
    if request.method == 'POST':
        form = SzczytForm(request.POST)
        if form.is_valid():
            szczyt = form.save()
            # Przetwarzaj dane lub podejmij inne działania, jeśli to konieczne
            return redirect('trasa')  # Przekieruj użytkownika na inną stronę po zapisaniu formularza
    else:
        form = SzczytForm()
    
    return render(request, 'trasa.html', {'form': form})

from .forms import WyprawaForm

@login_required
def dodaj_wyprawe(request):
    if request.method == 'POST':
        form = WyprawaForm(request.POST)
        if form.is_valid():
            wyprawa = form.save(commit=False)
            wyprawa.user = request.user  # Przypisanie użytkownika do wyprawy
            wyprawa.save()
            return redirect('lista_wypraw')
    else:
        form = WyprawaForm()

    return render(request, 'dodaj_wyprawe.html', {'form': form})

@login_required
def lista_wypraw(request):
    wyprawy = Wyprawa.objects.filter(user=request.user)
    return render(request, 'lista_wypraw.html', {'wyprawy': wyprawy})

@login_required
def ukoncz_wyprawe(request, wyprawa_id):
    wyprawa = Wyprawa.objects.get(id=wyprawa_id)
    wyprawa.ukonczona = not wyprawa.ukonczona  # Zmień status na przeciwny
    wyprawa.save()
    return redirect('lista_wypraw')

@login_required
def usun_wyprawe(request, wyprawa_id):
    try:
        wyprawa = Wyprawa.objects.get(id=wyprawa_id)
        wyprawa.delete()
    except Wyprawa.DoesNotExist:
         pass  # Jeśli wyprawa nie istnieje, można dodać odpowiednią obsługę błędu

    return redirect('lista_wypraw')

import smtplib
from email.mime.text import MIMEText
from django.shortcuts import render
from .forms import ZgloszenieForm 
from django.conf import settings
from django.contrib.auth.decorators import login_required
@login_required
def zgloszenie(request):
    if request.method == 'POST':
        form = ZgloszenieForm(request.POST)

        if form.is_valid():
            zgloszenie = form.save(commit=False)
            zgloszenie.user = request.user
            
            oddzial_id = request.POST.get('oddzial_ratowniczy')  # Pobranie przypisanego oddziału z formularza
            if oddzial_id:
                oddzial = OddzialRatowniczy.objects.get(pk=oddzial_id)
                zgloszenie.oddzial_ratowniczy = oddzial  # Przypisanie oddziału do zgłoszenia
            zgloszenie.save()

            # Logika wysyłania e-maila
            subject = 'Nowe zgłoszenie potrzeby pomocy'
            message = f'Zgłoszenie użytkownika {request.user.username} na trasie {zgloszenie.trasa.nazwa}.'
            from_email = 'm-hamela@wp.pl'
            recipient_list = ['michaal11123@gmail.com']

            send_mail(subject, message, from_email, recipient_list, fail_silently=False)

            # Przypisanie oddziału ratowniczego do zgłoszenia
            oddzial_id = request.POST.get('oddzial_ratowniczy')
            if oddzial_id:
                oddzial = OddzialRatowniczy.objects.get(pk=oddzial_id)
                zgloszenie.oddzial_ratowniczy = oddzial
                zgloszenie.save()

                messages.success(request, 'Zgłoszenie zostało pomyślnie zapisane z przypisanym oddziałem.')
            else:
                messages.warning(request, 'Zgłoszenie zostało zapisane, ale brakuje przypisanego oddziału.')

            print("E-mail został wysłany pomyślnie.")
        else:
            print(form.errors)
    else:
        form = ZgloszenieForm()

    return render(request, 'zgloszenie.html', {'form': form})

from .forms import PrzydzielOddzialRatunkowyForm

from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib import messages
from .models import Zgloszenie, OddzialRatowniczy
from .forms import PrzydzielOddzialRatunkowyForm

from django.core.mail import send_mail
from django.contrib import messages

def widok_ratownika(request):
    if request.user.groups.filter(name='Ratownicy').exists():
        if request.method == 'POST':
            zgloszenie_id = request.POST.get('zgloszenie_id')
            oddzial_id = request.POST.get('oddzial_ratunkowy')

            try:
                zgloszenie = Zgloszenie.objects.get(id=zgloszenie_id)
                oddzial = OddzialRatowniczy.objects.get(id=oddzial_id)

                # Sprawdź, czy oddział jest już przypisany do innego zgłoszenia
                oddzial_is_assigned = Zgloszenie.objects.filter(oddzial_ratowniczy=oddzial).exclude(id=zgloszenie_id).exists()
                if not oddzial_is_assigned:
                    zgloszenie.oddzial_ratowniczy = oddzial
                    zgloszenie.save()
                    messages.success(request, 'Oddział został przypisany do zgłoszenia.')

                    # Wysyłanie e-maila z informacją o przypisaniu oddziału
                    subject = 'Przypisanie oddziału ratowniczego'
                    if zgloszenie.user and hasattr(zgloszenie.user, 'username'):
                        user_username = zgloszenie.user.username
                    else:
                        user_username = "Nieznany użytkownik"
                    message = f'Oddział ratowniczy {oddzial.nazwa} został przypisany do zgłoszenia użytkownika {user_username} na trasie {zgloszenie.trasa.nazwa}.'

                    from_email = 'michaal11123@gmail.com'  # Zmień na swój e-mail
                    recipient_list = ['michaal11123@gmail.com']  # Zmień na adres e-mail oddziału

                    send_mail(
                        subject,
                        message,
                        from_email,
                        recipient_list,
                        fail_silently=False,  # Ustaw na True, aby ukryć błędy
                    )

                else:
                    messages.error(request, 'Ten oddział jest już przypisany do innego zgłoszenia.')

            except (Zgloszenie.DoesNotExist, OddzialRatowniczy.DoesNotExist):
                messages.error(request, 'Nieprawidłowe zgłoszenie lub oddział.')

        zgloszenia = Zgloszenie.objects.all()
        oddzialy = OddzialRatowniczy.objects.filter(zgloszenie=None)
        przydziel_form = PrzydzielOddzialRatunkowyForm()

        return render(request, 'widok_ratownika.html', {'zgloszenia': zgloszenia, 'oddzialy': oddzialy, 'uzytkownik': request.user, 'przydziel_form': przydziel_form})

    else:
        return render(request, 'brak_dostepu.html')


from django.shortcuts import render, redirect
from .forms import WyruszenieOddzialuForm
from .models import OddzialRatowniczy, Zgloszenie
from django.http import JsonResponse
from django.core.mail import send_mail

def zgloszenie_wyruszenia_oddzialu(request):
    if request.method == 'POST':
        form = WyruszenieOddzialuForm(request.POST)
        if form.is_valid():
            oddzial_id = form.cleaned_data['oddzial_ratunkowy']
            oddzial = OddzialRatowniczy.objects.get(id=oddzial_id)

            zgloszenie = oddzial.zgloszenie
            zgloszenie.wyruszyl_na_pomoc = True

Gory/templates/Szkolenia.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
</html>

Gory/templates/brak_dostepu.html
<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Brak Dostępu</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-image: url('/static/gory.jpg'); /* Ścieżka do obrazu w katalogu static */
            background-size: cover;
            background-repeat: no-repeat;
        }

        header {
            background-color: #130D29;
            color: #fff;
            padding: 10px 0;
        }

        nav {
            text-align: center;
        }

        ul {
            list-style-type: none;
            padding: 0;
            display: flex; /* Ustawienie menu na flexbox */
            justify-content: center; /* Wyśrodkowanie elementów menu */
            flex-wrap: wrap; /* Zawijanie elementów menu na mniejszych ekranach */
        }

        ul li {
            margin-right: 20px;
        }

        ul li:last-child {
            margin-right: 0;
        }

        a {
            text-decoration: none;
            color: #fff;
            font-size: 18px;
        }

        a:hover {
            border-bottom: 2px solid #fff;
        }

        a.btn {
            display: inline-block;
            background-color: #4e387e; /* Kolor przycisków */
            color: #fff;
            padding: 5px 10px;
            text-decoration: none;
            border-radius: 3px;
        }

        a.btn:hover {
            background-color: #6a4c93; /* Kolor przycisków po najechaniu myszką */
        }

        .container {
            max-width: 500px;
            margin: 0 auto;
            padding: 20px;
            background-color: rgba(255, 255, 255, 0.9);
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
        }
    </style>
</head>
<body>
    <header>
        <nav>
            <ul>
                <li><a href="#">Strona główna</a></li>
                <li><a href="#">O nas</a></li>
                <li><a href="#">Usługi</a></li>
                <li><a href="#">Kontakt</a></li>
            </ul>
        </nav>
    </header>
    <div class="container">
        <h1>Brak Dostępu</h1>
        <p>Przepraszamy, ale nie masz dostępu do tej strony.</p>
        <a href="#" class="btn">Powrót do strony głównej</a>
    </div>
</body>
</html>

Gory/templates/dodaj_wyprawe.html
<!DOCTYPE html>
<html>
<head>
    <title>Dodaj Wyprawę</title>
    <style>

@keyframes pulse {
            0% {
                transform: scale(1);
            }
            50% {
                transform: scale(1.1);
            }
            100% {
                transform: scale(1);
            }
        }

        @keyframes bounceIn {
            0% {
                opacity: 0;
                transform: translateY(-50px);
            }
            100% {
                opacity: 1;
                transform: translateY(0);
            }
        }

        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-image: url('/static/gory.jpg');
            background-size: cover;
            background-repeat: no-repeat;
        }

        header {
            background-color: #130D29;
            color: #fff;
            padding: 20px 0;
            text-align: center;
            margin-bottom: 20px;
        }

        nav ul {
            list-style-type: none;
            padding: 0;
            display: flex;
            justify-content: center;
            flex-wrap: wrap;
        }

        nav ul li {
            margin-right: 20px;
        }

        nav ul li:last-child {
            margin-right: 0;
        }

        nav a {
            text-decoration: none;
            color: #fff;
            font-size: 18px;
            transition: border-bottom 0.3s ease;
        }

        nav a:hover {
            border-bottom: 2px solid #fff;
        }

        .container {
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
            background-color: rgba(255, 255, 255, 0.8);
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
            animation: bounceIn 1s;

        }

        h1 {
            text-align: center;
            color: #130D29;
            text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.3);
            margin-bottom: 30px;
        }

        form {
            display: flex;
            flex-direction: column;
            align-items: center;
        }

        .form-group {
            width: 100%;
            margin-bottom: 20px;
        }

        label {
            display: block;
            font-weight: bold;
            color: #333;
            margin-bottom: 5px;
        }

        input[type="text"],
        select {
            width: calc(100% - 12px);
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
            transition: border-color 0.3s ease;
        }

        input[type="text"]:focus,
        select:focus {
            border-color: #130D29;
        }

        .button-container {
            display: flex;
            justify-content: space-between;
            margin-top: 20px;
        }

        .btn {
            display: inline-block;
            background-color: #4e387e;
            color: #fff;
            padding: 12px 24px;
            text-decoration: none;
            border-radius: 5px;
            transition: background-color 0.3s ease, box-shadow 0.3s ease;
            cursor: pointer;
        }

        .btn:hover {
            background-color: #6a4c93;
            transform: translateY(-2px);
        }

    </style>
</head>
<body>
    <header>
        <nav>
            <ul>
                <li><a href="{% url 'home' %}">O Nas</a></li>
                <li><a href="#">Szkolenia i Kursy</a></li>
                <li><a href="#">Ekwipunek i Technologia</a></li>
                <li><a href="#">Akcje Ratunkowe</a></li>
                <li><a href="#">Galeria</a></li>
                <li><a href="#">Kontakt</a></li>
                <li><a href="{% url 'zgloszenie' %}">Zgłoś Pomoc</a></li>
                <li><a href="{% url 'lista_wypraw' %}">Lista Wypraw</a></li>
                <li><a href="trasa">Trasy</a></li>
                {% if user.is_authenticated %}
                <li><a href="{% url 'logout' %}">Wyloguj</a></li>
                <li>Witaj, {{ user.username }}!</li>
                {% else %}
                <li><a href="{% url 'login' %}">Zaloguj</a></li>
                <li><a href="{% url 'register' %}">Zarejestruj</a></li>
    {% endif %}
        </ul>
            </ul>
        </nav>
        
    </header>
    <div class="container">
        <h1>Dodaj Wyprawę</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            
            
            <div class="button-container">
                <button type="submit" class="btn">
                    Dodaj Wyprawę
                </button>
                <a href="{% url 'home' %}" class="btn">
                    Powrót
                </a>
            </div>
        </form>
    </div>

    <script>
        flatpickr("#id_godzina_wyjscia", {
            enableTime: true,
            dateFormat: "Y-m-d H:i",
        });

        flatpickr("#id_godzina_zakonczenia", {
            enableTime: true,
            dateFormat: "Y-m-d H:i",
        });
    </script>
            
            
    </div>
</body>
</html>

Gory/templates/historia_oddzialow.html
<!DOCTYPE html>
<html>
<head>
    <title>Historia oddziałów dla zgłoszenia</title>
</head>
<body>
    <h1>Historia oddziałów dla zgłoszenia nr {{ zgloszenie.id }}</h1>

    <td>
        {% if zgloszenie.historia_oddzialow.exists %}
            <ul>
                {% for oddzial in zgloszenie.historia_oddzialow.all %}
                    <li>{{ oddzial.nazwa }}</li>
                {% endfor %}
            </ul>
        {% else %}
            Brak przydzielonych oddziałów
        {% endif %}
    </td>
</body>
</html>

Gory/templates/lista_wypraw.html
<!DOCTYPE html>
<html>
<head>
    <title>Lista Wypraw</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-image: url('/static/gory.jpg'); /* Ścieżka do obrazu w katalogu static */
            background-size: cover;
            background-repeat: no-repeat;
        }

        header {
            background-color: #130D29;
            color: #fff;
            padding: 10px 0;
        }

        nav {
            text-align: center;
        }

        ul {
            list-style-type: none;
            padding: 0;
            display: flex; /* Ustawienie menu na flexbox */
            justify-content: center; /* Wyśrodkowanie elementów menu */
            flex-wrap: wrap; /* Zawijanie elementów menu na mniejszych ekranach */
        }

        ul li {
            margin-right: 20px;
        }

        ul li:last-child {
            margin-right: 0;
        }

        a {
            text-decoration: none;
            color: #fff;
            font-size: 18px;
        }

        a:hover {
            border-bottom: 2px solid #fff;
        }

        a.btn {
            display: inline-block;
            background-color: #4e387e; /* Kolor przycisków */
            color: #fff;
            padding: 5px 10px;
            text-decoration: none;
            border-radius: 3px;
        }

        a.btn:hover {
            background-color: #6a4c93; /* Kolor przycisków po najechaniu myszką */
        }
    </style>
</head>
<body>
    <header>
        <nav>
            <ul>
                <li><a href="{% url 'home' %}">O Nas</a></li>
                <li><a href="#">Szkolenia i Kursy</a></li>
                <li><a href="#">Ekwipunek i Technologia</a></li>
                <li><a href="#">Akcje Ratunkowe</a></li>
                <li><a href="#">Galeria</a></li>
                <li><a href="#">Kontakt</a></li>
                <li><a href="{% url 'zgloszenie' %}">Zgłoś Pomoc</a></li>
                <li><a href="{% url 'lista_wypraw' %}">Lista Wypraw</a></li>
                <li><a href="trasa">Trasy</a></li>
                {% if user.is_authenticated %}
                <li><a href="{% url 'logout' %}">Wyloguj</a></li>
                <li>Witaj, {{ user.username }}!</li>
                {% else %}
                <li><a href="{% url 'login' %}">Zaloguj</a></li>
                <li><a href="{% url 'register' %}">Zarejestruj</a></li>
    {% endif %}
        </ul>
            </ul>
    </header>

    <ul>
        {% for wyprawa in wyprawy %}
            <li style="list-style: none; background: #f3f3f3; padding: 15px; margin: 10px; border-radius: 5px; box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.2); display: flex; justify-content: space-between; align-items: center;">
                <div>
                    <strong>Nazwa szczytu:</strong> {{ wyprawa.nazwa_szczytu }}<br>
                    <strong>Godzina wyjścia:</strong> {{ wyprawa.godzina_wyjscia }}<br>
                    <strong>Godzina zakończenia:</strong> {{ wyprawa.godzina_zakonczenia }}<br>
                    <strong>Czas trwania:</strong> {{ wyprawa.czas_trwania }} minut<br>
                    {% if wyprawa.ukonczona %}
                        <strong>Status:</strong> Ukończona<br>
                        <a href="{% url 'ukoncz_wyprawe' wyprawa.id %}" class="btn" style="background: #e74c3c; color: #fff;">Oznacz jako nieukończona</a>
                    {% else %}
                        <strong>Status:</strong> Nieukończona<br>
                        
                        <a href="{% url 'ukoncz_wyprawe' wyprawa.id %}" class="btn" style="background: #2ecc71; color: #fff;">Oznacz jako ukończona</a>
                        
                    {% endif %}
                    <div>
                        <a href="{% url 'usun_wyprawe' wyprawa.id %}" class="btn" style="background: #e74c3c; color: #fff;">Usuń Wyprawę</a>
                    </div>
                </div>
                
            </li>
        {% empty %}
            <p>Brak dodanych wypraw.</p>
        {% endfor %}
    </ul>
</body>
</html>

Gory/templates/navbar.html
<span>Hello</span>
<span><a href="{% url 'logout' %}"></a></span>